- id: doi:10.1021/acscentsci.5c00707
  title: "High-Throughput Discovery of Ferrocene Mechanophores with Enhanced Reactivity and Network Toughening"
  authors:
  - <b>Kevlishvili Ilia</b>
  - Jafer Vakil
  - Kastner David
  - Huang Xiao
  - Craig Stephen
  - Kulik Heather
  image: ../images/ferrocene.jpg
